In [1]:
pip install requests pandas

Requirement already satisfied: requests in c:\users\pranathi\anaconda3\lib\site-packages (2.32.5)
Requirement already satisfied: pandas in c:\users\pranathi\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\pranathi\anaconda3\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pranathi\anaconda3\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\pranathi\anaconda3\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pranathi\anaconda3\lib\site-packages (from requests) (2026.1.4)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pranathi\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pranathi\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pranathi\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pranathi\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\pranathi\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import requests
import pandas as pd

In [3]:
!pip install requests pandas

Requirement already satisfied: requests in c:\users\pranathi\anaconda3\lib\site-packages (2.32.5)
Requirement already satisfied: pandas in c:\users\pranathi\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\pranathi\anaconda3\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pranathi\anaconda3\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\pranathi\anaconda3\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pranathi\anaconda3\lib\site-packages (from requests) (2026.1.4)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pranathi\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pranathi\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pranathi\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pranathi\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\pranathi\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
import matplotlib.pyplot as plt

In [6]:
API_KEY = " 33hBmIT7Sk4F5geRwjlONYrtlo60CFc40e5pgfF6"

In [7]:
url = "https://api.eia.gov/v2/electricity/retail-sales/data/"

In [8]:
params = {
    "api_key": "33hBmIT7Sk4F5geRwjlONYrtlo60CFc40e5pgfF6",
    "frequency": "monthly",
    "data[0]": "sales",
    "facets[sectorid][]": "RES",
    "start": "2015-01",
    "sort[0][column]": "period",
    "sort[0][direction]": "asc",
    "offset": 0,
    "length": 5000
}

In [9]:
response = requests.get(url, params=params)
data = response.json()

In [10]:
data.keys()

dict_keys(['warnings', 'response', 'request', 'apiVersion', 'ExcelAddInVersion'])

In [11]:
data["response"].keys()

dict_keys(['total', 'dateFormat', 'frequency', 'data', 'description'])

In [12]:
records = data["response"]["data"]

In [13]:
import pandas as pd

df = pd.DataFrame(records)
df.head()

,period,stateid,stateDescription,sectorid,sectorName,sales,sales-units
0,2015-01,AK,Alaska,RES,residential,218.93683,million kilowatt hours
1,2015-01,AL,Alabama,RES,residential,3250.39739,million kilowatt hours
2,2015-01,AR,Arkansas,RES,residential,1894.25931,million kilowatt hours
3,2015-01,AZ,Arizona,RES,residential,2342.84715,million kilowatt hours
4,2015-01,CA,California,RES,residential,7593.50718,million kilowatt hours

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   period            5000 non-null   object
 1   stateid           5000 non-null   object
 2   stateDescription  5000 non-null   object
 3   sectorid          5000 non-null   object
 4   sectorName        5000 non-null   object
 5   sales             5000 non-null   object
 6   sales-units       5000 non-null   object
dtypes: object(7)
memory usage: 273.6+ KB

In [15]:
df.shape

(5000, 7)

In [16]:
df.isnull().sum()

period              0
stateid             0
stateDescription    0
sectorid            0
sectorName          0
sales               0
sales-units         0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
(df == "").sum()

period              0
stateid             0
stateDescription    0
sectorid            0
sectorName          0
sales               0
sales-units         0
dtype: int64

In [19]:
df["stateid"].unique()

array(['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'ENC', 'ESC',
       'FL', 'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA',
       'MAT', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'MTN', 'NC', 'ND',
       'NE', 'NEW', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA',
       'PACC', 'PACN', 'RI', 'SAT', 'SC', 'SD', 'TN', 'TX', 'US', 'UT',
       'VA', 'VT', 'WA', 'WI', 'WNC', 'WSC', 'WV', 'WY'], dtype=object)

In [20]:
df["stateDescription"].unique()

array(['Alaska', 'Alabama', 'Arkansas', 'Arizona', 'California',
       'Colorado', 'Connecticut', 'District of Columbia', 'Delaware',
       'East North Central', 'East South Central', 'Florida', 'Georgia',
       'Hawaii', 'Iowa', 'Idaho', 'Illinois', 'Indiana', 'Kansas',
       'Kentucky', 'Louisiana', 'Massachusetts', 'Middle Atlantic',
       'Maryland', 'Maine', 'Michigan', 'Minnesota', 'Missouri',
       'Mississippi', 'Montana', 'Mountain', 'North Carolina',
       'North Dakota', 'Nebraska', 'New England', 'New Hampshire',
       'New Jersey', 'New Mexico', 'Nevada', 'New York', 'Ohio',
       'Oklahoma', 'Oregon', 'Pennsylvania', 'Pacific Contiguous',
       'Pacific Noncontiguous', 'Rhode Island', 'South Atlantic',
       'South Carolina', 'South Dakota', 'Tennessee', 'Texas',
       'U.S. Total', 'Utah', 'Virginia', 'Vermont', 'Washington',
       'Wisconsin', 'West North Central', 'West South Central',
       'West Virginia', 'Wyoming'], dtype=object)

In [21]:
df["sectorid"].unique()

array(['RES'], dtype=object)

In [22]:
df["sectorName"].unique()

array(['residential'], dtype=object)

In [23]:
df["sales-units"].unique()

array(['million kilowatt hours'], dtype=object)

In [24]:
df["period"] = pd.to_datetime(df["period"])

In [25]:
df["sales"] = pd.to_numeric(df["sales"], errors = "coerce")

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   period            5000 non-null   datetime64[ns]
 1   stateid           5000 non-null   object
 2   stateDescription  5000 non-null   object
 3   sectorid          5000 non-null   object
 4   sectorName        5000 non-null   object
 5   sales             5000 non-null   float64
 6   sales-units       5000 non-null   object
dtypes: datetime64[ns](1), float64(1), object(5)
memory usage: 273.6+ KB

In [27]:
df.head()

,period,stateid,stateDescription,sectorid,sectorName,sales,sales-units
0,2015-01-01,AK,Alaska,RES,residential,218.93683,million kilowatt hours
1,2015-01-01,AL,Alabama,RES,residential,3250.39739,million kilowatt hours
2,2015-01-01,AR,Arkansas,RES,residential,1894.25931,million kilowatt hours
3,2015-01-01,AZ,Arizona,RES,residential,2342.84715,million kilowatt hours
4,2015-01-01,CA,California,RES,residential,7593.50718,million kilowatt hours

In [28]:
df.tail()

,period,stateid,stateDescription,sectorid,sectorName,sales,sales-units
4995,2021-09-01,NH,New Hampshire,RES,residential,402.22601,million kilowatt hours
4996,2021-09-01,NJ,New Jersey,RES,residential,2595.74060,million kilowatt hours
4997,2021-09-01,NM,New Mexico,RES,residential,618.83299,million kilowatt hours
4998,2021-09-01,NV,Nevada,RES,residential,1474.44336,million kilowatt hours
4999,2021-09-01,NY,New York,RES,residential,4932.43760,million kilowatt hours

In [29]:
df_sorted = df.sort_values("period")

In [30]:
(df_sorted["period"].diff().dt.days < 0).sum()

np.int64(0)

In [31]:
df_sorted["period"].is_monotonic_increasing

True

In [32]:
full_range = pd.date_range(
    start=df["period"].min(),
    end=df["period"].max(),
    freq="MS"
)

In [33]:
missing_dates = full_range.difference(df["period"])
missing_dates

DatetimeIndex([], dtype='datetime64[ns]', freq='MS')

In [34]:
df['sales'].describe()

count      5000.000000
mean       5778.354834
std       15721.429133
min         124.522000
25%         732.391538
50%        2087.053765
75%        4428.123750
max      167108.141570
Name: sales, dtype: float64

print(full_range)

In [35]:
type(full_range)

pandas.core.indexes.datetimes.DatetimeIndex

In [36]:
df['period'].min(), df['period'].max()

(Timestamp('2015-01-01 00:00:00'), Timestamp('2021-09-01 00:00:00'))

In [37]:
list(full_range)[:10]

[Timestamp('2015-01-01 00:00:00'),
 Timestamp('2015-02-01 00:00:00'),
 Timestamp('2015-03-01 00:00:00'),
 Timestamp('2015-04-01 00:00:00'),
 Timestamp('2015-05-01 00:00:00'),
 Timestamp('2015-06-01 00:00:00'),
 Timestamp('2015-07-01 00:00:00'),
 Timestamp('2015-08-01 00:00:00'),
 Timestamp('2015-09-01 00:00:00'),
 Timestamp('2015-10-01 00:00:00')]

In [38]:
df[df['sales'] <= 0]

Empty DataFrame
Columns: [period, stateid, stateDescription, sectorid, sectorName, sales, sales-units]
Index: []

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   period            5000 non-null   datetime64[ns]
 1   stateid           5000 non-null   object
 2   stateDescription  5000 non-null   object
 3   sectorid          5000 non-null   object
 4   sectorName        5000 non-null   object
 5   sales             5000 non-null   float64
 6   sales-units       5000 non-null   object
dtypes: datetime64[ns](1), float64(1), object(5)
memory usage: 273.6+ KB

In [40]:
df.duplicated(subset=["stateid", "period"]).sum()

np.int64(0)

In [41]:
df["sales-units"].value_counts()

sales-units
million kilowatt hours    5000
Name: count, dtype: int64

In [43]:
print(pd.__version__)

2.3.3